Fix some type instabilities and add CI
rdoelman/ZernikePolynomials.jl pull request #3
Opened 2022-06-03 08:51 UTC by roflmaostc

Hi!

I tried to fix some of the type instabilities. That also improved performance quite a bit:

Current state:
```julia
julia> using ZernikePolynomials

julia> x = randn((2000,));

julia> y = x';

julia> using BenchmarkTools

julia> @btime Zernike(10, coord=:cartesian, index=:OSA).($x,$y);
  605.860 ms (16000026 allocations: 457.76 MiB)
```

New state:
```julia
julia> using ZernikePolynomials
[ Info: Precompiling ZernikePolynomials [e462d300-c971-11e9-30f1-fb93b1f8f73a]

julia> x = randn((2000,));

julia> y = x';

julia> using BenchmarkTools

julia> @btime Zernike(10, coord=:cartesian, index=:OSA).($x,$y);
  165.865 ms (6 allocations: 30.52 MiB)
```

I would be happy to incorporate your feedback!

Best,

Felix

2022-06-03 12:03 UTC, rdoelman commented on src/ZernikePolynomials.jl
> +        # throw an error instead of NaN because of type instability
I agree with the change, but the comment line is then not necessary.

2022-06-03 12:16 UTC, rdoelman requested changes
These are really nice improvements!

Any chance you can make the indentation (2 spaces vs tab/4spaces) consistent throughout ZernikePolynomials.jl?

2022-06-03 12:43 UTC, roflmaostc commented
Should we switch everything to 4 space?

There is another type stability issue because we return different functions at [this line](https://github.com/roflmaostc/ZernikePolynomials.jl/blob/a82953ca80e81d02b69b22154381fd0b5c77caf1/src/ZernikePolynomials.jl#L259).

I try to tackle that next week

2022-06-07 11:10 UTC, roflmaostc commented
I think this type stability issue, we can leave it like that.
Otherwise, the code gets more complicated and less efficient in certain circumstances.

2022-06-07 11:12 UTC, rdoelman approved these changes

2022-06-07 11:14 UTC, rdoelman commented
Thanks so much!

2022-06-07 11:14 UTC, merged